sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - nightly
deploy:
  provider: heroku
  api_key:
    secure: UsLwPC+7Ui9QAJIhvfKjRxfDb6Fjuf8VDq/yxyXj7upyol5AcTEdOwYOh39Ka/WG9QQF+f9V6zkbzqbTk4PWBlC+Dnfmm+LB9j1/UtH3Ce9179wFdVGxnN7v/nR+HIdl4lFodPYxYe53ZCW2zH+rFgkBq370oIEPq4rH1SALmqjwr+/LszTZXozg2ZzQPxw56QszPexd5n7m5OVLoRJmHrVapcvEcOMxAu4kjLEFDWuwrwRZF3EJiBKTuBY5yvaFegvfvSerwjQZmTIQcDtPrScPpp82obdglTpCpec/ImrWuybpSptj1zlNMgtZwwv0zoE9PkuznmYB/CLz0D4bj8xqpSQOlBeRLbeJXcTzxMJQCZ+lhCnocwLUdjISuF89hQqVeU5N8qu5GdqL9mnQ6KXgbHkBWAA9TPUZyqVbqRZ891u8vpXZ8BZCqR4rmMYMJn8dbExGprLnKeWA36cXwwJ5NaPAqjCPO5fKHPV0gbaFw8EVRE2koMzJhMFlkVlxzRHL7CQYeULDupDnToZULydL6cBglwAh/1C+7v7325Tcjf6ekV6aKZu/59vWGexq7Q128Epljc84Fee6StKSuSMBUGvLewCIjq7L09o3O1PIkegJpAgtSlgMuXm/08Mi3+et1p4fRNGjNUyEeSqowVLIHirqtOfkIJrIJySSPYc=
  app: nightly-42
  on:
    repo: frontend-park-mail-ru/2017_2_42
    branch: nightly
