sudo: required
dist: trusty
language: node_js
node_js: 8
branches:
  only:
  - nightly
  - master
  - sandbox
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 194.87.110.17 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/technopark.pub
- npm run build
- scp -r ./public fourtytwo@physicsio.tech:/home/fourtytwo/frontend
before_install:
- openssl aes-256-cbc -K $encrypted_4f2cef819b27_key -iv $encrypted_4f2cef819b27_iv
  -in technopark.pub.enc -out $HOME/.ssh/technopark.pub -d
