language: node_js
node_js: 8
branches:
  only:
  - nightly
  - master
  - sandbox
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 194.87.110.17 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/technopark
- npm run build
- yes | scp -r ./public -o StrictHostKeyChecking=no fourtytwo@194.87.110.17:/home/fourtytwo/frontend
before_install:
- openssl aes-256-cbc -K $encrypted_4f2cef819b27_key -iv $encrypted_4f2cef819b27_iv
  -in technopark.enc -out ~\/.ssh/technopark -d
- openssl aes-256-cbc -K $encrypted_4f2cef819b27_key -iv $encrypted_4f2cef819b27_iv
  -in technopark.enc -out $HOME/.ssh/technopark -d
