sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - nightly
deploy:
  provider: heroku
  api_key:
    secure: Ylyovm3En1Q0Ng1ARyBxsPKDvFIJwmNRsAquO3PIyp43NE5wnclw0KM3C16tlSEeGY8blRbdzZ7cKzWWRQ1IOfKJYuuuPEbb3a+wvzgwlk6cfZ0/dvZcHhAOXp+Er8WyrHwOhSQtjsr0kW0mH6WL1/Ilzjt9hy8q66q0cvTwU2kuC3bPOsqdLhQtCXM8NPO7OGJQbsJOJMdRykR9hPxxvuLPvwX6tWTWftKNOVoaNznDxkTWEYaaZ04iyfCJL8t99rrGWPw8s7CmKcf8fEfPlcRvmDbcBMvgSj7pEewQ/sOdmzekXIHoOduI8X138hqmMIVNWWQsFCDftoOEZiSsncqjr3IojPjV2cxuB5AuShJyf5VhrclycWEtB4QgTIIQCWZUf63dqgktu9ZBOhkHv18jIp28fd2wPRtA2tfoGZNcjECCJQ41K9ERvkI294UXR1runcXA9CtvX7MP46MrB9DITmHJl/w620d/lexdkFeM/aAVvxhdEbO/5psirBcmV+Qm3qKO9kuT/5HKw5oLfteiB2Lt66+OBl7abd8h21/3QRGMeFZQj4m1NoYlUVqLRH0YS1bpRt1SSO4qVdk1urg2Ur+pbJXqTDyPtRUkamQ1J5MUHDABPhgZOl7CuApk7ANs3h1FglwA1xOoLBQHgAKg6t5RPOfDGrRCm0Qxq0A=
  app: niglhtly-42
  on:
    repo: frontend-park-mail-ru/2017_2_42
    branch: nightly
