language: node_js
node_js:
- '8'
branches:
  only:
  - nightly
  - master
  - sandbox
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 194.87.110.17 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/id_rsa
- ssh-add $HOME/.ssh/id_rsa
- npm run build
- scp -r ./dist fourtytwo@194.87.110.17:~/frontend
before_install:
- openssl aes-256-cbc -K $encrypted_cff8668a0280_key -iv $encrypted_cff8668a0280_iv
  -in id_rsa.enc -out $HOME/.ssh/id_rsa -d
