sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - sandbox
deploy:
  provider: heroku
  api_key:
    secure: fB+TsTTWV/jitYhXCS3Xovv8/H1ss42tAlFCg6Dd2vpRGr5/fyiPKgy4uCxFdsPSmonSyVosj3ENjZeMtaH95d5Svza16js4puL7tC5809jKo2xZhy2mhUCwJuv/ZLjlduBTEgxmCaI4U6mR7e7VXMcFkwL6E6/7dOSoOOup9UDtL/7eIvohGqLOPss+i7txffRSpCyHWh1L3VR2FErjCbD+TLlLeqsKUV853pjAAorKF6OQWSTAaw1grzVATriK237bbUuRRcuENrA2diNxGQ0gTMkzfE3eaUHommaZhsCgqiVsKsqyA/9o1VVsa1sKUNZRP2hLuXYtg8quDVuzmSvMW+AawC1T4045LcfOBx8aFRKdFlnwuqvPVi5pedbyNxaC39p5IJQwGcyqhO1FX/cKF3KX/5XuWP8/CRJ+Ow0XawdfLAJJ3szO/fkr5HpP3Q9qum2fB8NK8d+K1HxZvxD1qewU+8cMWwdVnWy5svTMNsRjILwkPVTGB/NPWVgVL9zdQ+yLlSY6RUJ6N2krGU4xcbp0gumCRp41aVkk9BN5BQQWT6MJSz4DDlq5MSUQrATCo5/bDEihaxHIbtRuRQNstIzfWzntx975b4DK/IxDBTZMxoU2jZjFmIzNtiHOJt87TvAA2xRwes77v4JvVlpdBJxm8cttKWfOStMIc7E=
  app: sand42box
  on:
    repo: frontend-park-mail-ru/2017_2_42
    branch: sandbox
